const LOGIN_SUCCESS = "LOGIN_SUCCESS"
const LOGIN_ERROR = "LOGIN_ERROR"
const LOGIN_LOADING = "LOGIN_LOADING"
const POST_USER_LOADING = "POST_USER_LOADING"
const POST_USER_SUCCESS = "POST_USER_SUCCESS"
const POST_USER_ERROR = "POST_USER_ERROR"

export {
    LOGIN_SUCCESS,
    LOGIN_ERROR,
    LOGIN_LOADING,
    POST_USER_ERROR,
    POST_USER_SUCCESS,
    POST_USER_LOADING,
}